name: Build and Pack 'dev'

on:
    push:
        branches:
            - 'feature/GitHubActions'
        paths-ignore:
            - '**/*.md'
            - 'mkdocs.yml'
            - 'src/docs/**/*'

jobs:
    ci-pipeline:
        name: 'Continuous Integration pipeline'
        runs-on: 'windows-latest'
        env:
            DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
        steps:
            - name: Initialize
              run: |
                echo .NET Core & dotnet --version & echo.
                echo NodeJS & node --version & echo.
                echo NPM & npm version & echo.
                git config --global core.autocrlf true
              shell: cmd
#            - name: Restore NuGet packages
#              run: dotnet restore OrchardCore.sln
#              shell: cmd
            - name: Build solution
              run: dotnet build OrchardCore.sln -c Release
              shell: cmd
            - name: Pack solution
              run: dotnet pack OrchardCore.sln -c Release --no-build
              shell: cmd
            - name: Run tests
              run: |
                dotnet test .\test\OrchardCore.Tests\OrchardCore.Tests.csproj -c Release --no-build
                cd .\test\Functional
                test-setup.cmd
                test-run.cmd